AWSTemplateFormatVersion: "2010-09-09"
Description: S3 static website.

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "static-site-${AWS::AccountId}"
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForWebsite
            Effect: Allow
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref StaticSiteBucket

  WebsiteURL:
    Description: S3 website endpoint
    Value: !GetAtt StaticSiteBucket.WebsiteURL